// Package fastjson's Schubfach float64→string formatter.
//
// Ported from ByteDance sonic's native/f64toa.c, which is in turn a port of
// Alexander Bolz's Schubfach reference C++ implementation at
// https://github.com/abolz/Drachennest.
//
// ---
// Copyright 2020 Alexander Bolz
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//
// This file may have been modified by ByteDance authors. All ByteDance
// Modifications are Copyright 2022 ByteDance Authors.
// ---
//
// Paper reference: Raffaello Giulietti, "The Schubfach way to render
// doubles" (2022-03-20). Schubfach is strictly shorter than Ryu for the
// float64 shortest-representation problem — one 128-bit multiply plus a
// round-odd step instead of Ryu's three multiplies plus exact-bits search.
package fastjson

import (
	"math"
	"math/bits"
)

const (
	f64ExpBits    = 11
	f64SigBits    = 52
	f64ExpMask    = 0x7FF0000000000000
	f64SigMask    = 0x000FFFFFFFFFFFFF
	f64ExpBias    = 1023
	f64InfNanExp  = 0x7FF
	f64HiddenBit  = 0x0010000000000000
)

// digits is the two-ASCII-byte lookup for 00..99. `digits[2k]` and
// `digits[2k+1]` are the tens and ones digit of k respectively.
var digits = [200]byte{
	'0', '0', '0', '1', '0', '2', '0', '3', '0', '4', '0', '5', '0', '6', '0', '7', '0', '8', '0', '9',
	'1', '0', '1', '1', '1', '2', '1', '3', '1', '4', '1', '5', '1', '6', '1', '7', '1', '8', '1', '9',
	'2', '0', '2', '1', '2', '2', '2', '3', '2', '4', '2', '5', '2', '6', '2', '7', '2', '8', '2', '9',
	'3', '0', '3', '1', '3', '2', '3', '3', '3', '4', '3', '5', '3', '6', '3', '7', '3', '8', '3', '9',
	'4', '0', '4', '1', '4', '2', '4', '3', '4', '4', '4', '5', '4', '6', '4', '7', '4', '8', '4', '9',
	'5', '0', '5', '1', '5', '2', '5', '3', '5', '4', '5', '5', '5', '6', '5', '7', '5', '8', '5', '9',
	'6', '0', '6', '1', '6', '2', '6', '3', '6', '4', '6', '5', '6', '6', '6', '7', '6', '8', '6', '9',
	'7', '0', '7', '1', '7', '2', '7', '3', '7', '4', '7', '5', '7', '6', '7', '7', '7', '8', '7', '9',
	'8', '0', '8', '1', '8', '2', '8', '3', '8', '4', '8', '5', '8', '6', '8', '7', '8', '8', '8', '9',
	'9', '0', '9', '1', '9', '2', '9', '3', '9', '4', '9', '5', '9', '6', '9', '7', '9', '8', '9', '9',
}

// schubfachDec is the decoded Schubfach intermediate: sig * 10^exp.
type schubfachDec struct {
	sig uint64
	exp int32
}

// ctz10 returns the number of decimal digits in v (must be in [1, 1e17]).
func ctz10(v uint64) int {
	if v >= 10000000000 {
		switch {
		case v < 100000000000:
			return 11
		case v < 1000000000000:
			return 12
		case v < 10000000000000:
			return 13
		case v < 100000000000000:
			return 14
		case v < 1000000000000000:
			return 15
		case v < 10000000000000000:
			return 16
		default:
			return 17
		}
	}
	switch {
	case v < 10:
		return 1
	case v < 100:
		return 2
	case v < 1000:
		return 3
	case v < 10000:
		return 4
	case v < 100000:
		return 5
	case v < 1000000:
		return 6
	case v < 10000000:
		return 7
	case v < 100000000:
		return 8
	case v < 1000000000:
		return 9
	default:
		return 10
	}
}

// roundOdd computes the Schubfach round-odd step: returns y1 | (y0 > 1)
// where y = cp * (pow10Hi:pow10Lo) >> 64, done in 128 bits.
func roundOdd(pow10Hi, pow10Lo, cp uint64) uint64 {
	// x = cp * pow10Lo (128 bits)
	xHi, _ := bits.Mul64(cp, pow10Lo)
	// y = cp * pow10Hi + xHi  (128 bits)
	yHi, yLo := bits.Mul64(cp, pow10Hi)
	yLoSum, carry := bits.Add64(yLo, xHi, 0)
	yHi, _ = bits.Add64(yHi, 0, carry)
	y0 := yLoSum
	y1 := yHi
	if y0 > 1 {
		return y1 | 1
	}
	return y1
}

// f64todec applies the Schubfach algorithm to the raw float64 bits.
// Returns dec such that fp ≈ sig * 10^exp (the exact-shortest form).
func f64todec(rsig uint64, rexp int32, c uint64, q int32) schubfachDec {
	even := c&1 == 0
	irregular := rsig == 0 && rexp > 1

	cbl := 4*c - 2
	if irregular {
		cbl = 4*c - 1
	}
	cb := 4 * c
	cbr := 4*c + 2

	// k = irregular ? floor(log10(3/4 * 2^q)) : floor(log10(2^q))
	var k int32
	if irregular {
		k = (q*1262611 - 524031) >> 22
	} else {
		k = (q * 1262611) >> 22
	}

	h := q + (((-k) * 1741647) >> 19) + 1

	// pow10_ceil_sig lookup: index is (-k) shifted by schubfachKMin.
	idx := -k - schubfachKMin
	pow10Hi := schubfachPow10CeilSig[idx][0]
	pow10Lo := schubfachPow10CeilSig[idx][1]

	vbl := roundOdd(pow10Hi, pow10Lo, cbl<<uint(h))
	vb := roundOdd(pow10Hi, pow10Lo, cb<<uint(h))
	vbr := roundOdd(pow10Hi, pow10Lo, cbr<<uint(h))

	lower := vbl
	upper := vbr
	if !even {
		lower++
		upper--
	}

	s := vb / 4
	if s >= 10 {
		// R_{k+1} may contain up or wp.
		sp := s / 10
		upInside := lower <= 40*sp
		wpInside := 40*sp+40 <= upper
		if upInside != wpInside {
			exp := k + 1
			if wpInside {
				return schubfachDec{sig: sp + 1, exp: exp}
			}
			return schubfachDec{sig: sp, exp: exp}
		}
	}

	uInside := lower <= 4*s
	wInside := 4*s+4 <= upper
	if uInside != wInside {
		if wInside {
			return schubfachDec{sig: s + 1, exp: k}
		}
		return schubfachDec{sig: s, exp: k}
	}

	// Both u and w inside: round to nearest, tie to even.
	mid := 4*s + 2
	roundUp := vb > mid || (vb == mid && s&1 != 0)
	if roundUp {
		return schubfachDec{sig: s + 1, exp: k}
	}
	return schubfachDec{sig: s, exp: k}
}

// writeDigits fills exactly cnt decimal digits of sig into dst[0:cnt],
// most-significant first. dst must have length ≥ cnt.
// If trimTrailingZeros is true, returns the number of non-zero tail
// digits produced (so caller can shorten the emitted range); otherwise
// returns cnt verbatim. Trailing zeros, when trimmed, are in blocks of
// 8 (matching sonic's trick — only the outermost 8 digits are tested
// for being all-zero).
func writeDigits(sig uint64, dst []byte, cnt int, trimTrailingZeros bool) int {
	p := cnt
	ctz := 0

	if (sig >> 32) != 0 {
		q := sig / 100000000
		r := uint32(sig) - 100000000*uint32(q)
		sig = q
		if trimTrailingZeros && r == 0 {
			ctz += 8
		} else {
			c := r % 10000
			r /= 10000
			d := r % 10000
			c0 := (c % 100) << 1
			c1 := (c / 100) << 1
			d0 := (d % 100) << 1
			d1 := (d / 100) << 1
			dst[p-2] = digits[c0]
			dst[p-1] = digits[c0+1]
			dst[p-4] = digits[c1]
			dst[p-3] = digits[c1+1]
			dst[p-6] = digits[d0]
			dst[p-5] = digits[d0+1]
			dst[p-8] = digits[d1]
			dst[p-7] = digits[d1+1]
		}
		p -= 8
	}

	sig2 := uint32(sig)
	for sig2 >= 10000 {
		c := sig2 - 10000*(sig2/10000)
		sig2 /= 10000
		c0 := (c % 100) << 1
		c1 := (c / 100) << 1
		dst[p-2] = digits[c0]
		dst[p-1] = digits[c0+1]
		dst[p-4] = digits[c1]
		dst[p-3] = digits[c1+1]
		p -= 4
	}
	if sig2 >= 100 {
		c := (sig2 % 100) << 1
		sig2 /= 100
		dst[p-2] = digits[c]
		dst[p-1] = digits[c+1]
		p -= 2
	}
	if sig2 >= 10 {
		c := sig2 << 1
		dst[p-2] = digits[c]
		dst[p-1] = digits[c+1]
	} else {
		dst[0] = byte('0' + sig2)
	}
	return cnt - ctz
}

// appendNBytes extends out by n zero bytes and returns (out, startIndex).
func appendNBytes(out []byte, n int) ([]byte, int) {
	start := len(out)
	for i := 0; i < n; i++ {
		out = append(out, 0)
	}
	return out, start
}

// formatExponent writes v in scientific form: d.dddde±NN. Appends to
// out and returns the extended slice.
func formatExponent(dec schubfachDec, out []byte, cnt int) []byte {
	// Write cnt significand digits into a scratch area past out's end,
	// then reorder to put the first digit before the '.'.
	out, start := appendNBytes(out, cnt)
	n := writeDigits(dec.sig, out[start:start+cnt], cnt, true)
	// out[start:start+n] now contains the trimmed significand digits.
	// We want: out[start] = first digit, out[start+1] = '.',
	// out[start+2 ...] = rest of significand.
	if n > 1 {
		// Move digits [start+1 : start+n] right by 1 to make room for '.'.
		// But since all live bytes are within [start:start+cnt] and
		// start+cnt might equal len(out), we need to grow.
		out = append(out, 0)
		copy(out[start+2:], out[start+1:start+n])
		out[start+1] = '.'
		out = out[:start+n+1] // first-digit + '.' + (n-1) digits
	} else {
		out = out[:start+1] // just the single digit
	}
	out = append(out, 'e')
	exp := dec.exp + int32(cnt) - 1
	if exp < 0 {
		out = append(out, '-')
		exp = -exp
	} else {
		out = append(out, '+')
	}
	if exp >= 100 {
		c := exp % 10
		idx := (exp / 10) * 2
		out = append(out, digits[idx], digits[idx+1], byte('0'+c))
	} else if exp >= 10 {
		idx := exp * 2
		out = append(out, digits[idx], digits[idx+1])
	} else {
		out = append(out, byte('0'+exp))
	}
	return out
}

// formatDecimal writes v in fixed-point notation with a decimal point.
func formatDecimal(dec schubfachDec, out []byte, cnt int) []byte {
	point := cnt + int(dec.exp)

	if point <= 0 {
		// "0.000…0dddd" — leading zero, point, -point leading-zero fraction.
		out = append(out, '0', '.')
		for i := 0; i < -point; i++ {
			out = append(out, '0')
		}
		out, start := appendNBytes(out, cnt)
		n := writeDigits(dec.sig, out[start:start+cnt], cnt, true)
		return out[:start+n]
	}

	// point > 0: integer part has `point` digits. Significand has `cnt`
	// digits total; if cnt > point, fraction exists.
	out, start := appendNBytes(out, cnt)
	n := writeDigits(dec.sig, out[start:start+cnt], cnt, true)
	// out[start:start+n] holds the significand (trailing zeros trimmed).
	end := start + n
	if n > point {
		// Insert '.' at out[start+point], shifting [start+point:end] right 1.
		out = append(out, 0)
		copy(out[start+point+1:], out[start+point:end])
		out[start+point] = '.'
		end++
	} else {
		// Pad integer part with zeros (n <= point).
		for i := 0; i < point-n; i++ {
			out = append(out, '0')
			end++
		}
	}
	return out[:end]
}

// writeDec is the Schubfach "format decision" wrapper: pick scientific
// vs. decimal based on the magnitude.
func writeDec(dec schubfachDec, out []byte) []byte {
	cnt := ctz10(dec.sig)
	dot := cnt + int(dec.exp)
	sciExp := dot - 1
	expFmt := sciExp < -6 || sciExp > 20
	hasDot := dot < cnt

	if expFmt {
		return formatExponent(dec, out, cnt)
	}
	if hasDot {
		return formatDecimal(dec, out, cnt)
	}
	// Pure integer (possibly trailing zeros to reach `dot` width).
	out, start := appendNBytes(out, dot)
	writeDigits(dec.sig, out[start:start+cnt], cnt, false)
	for i := start + cnt; i < start+dot; i++ {
		out[i] = '0'
	}
	return out
}

// schubfachAppendFloat64 appends the decimal representation of f to out.
// Matches the general contract of strconv.AppendFloat(_, f, 'g', -1, 64)
// but with Schubfach-style exponent-format gating (matches sonic's
// choice: 'e' when scientific exponent < -6 or > 20).
func schubfachAppendFloat64(out []byte, f float64) []byte {
	raw := f64bits(f)
	neg := raw>>63 != 0
	rsig := raw & f64SigMask
	rexp := int32((raw & f64ExpMask) >> f64SigBits)

	// NaN/Inf: caller checks, but for safety return empty.
	if rexp == f64InfNanExp {
		return out
	}

	if neg {
		out = append(out, '-')
	}

	// zero
	if raw<<1 == 0 {
		return append(out, '0')
	}

	var c uint64
	var q int32
	if rexp != 0 {
		c = rsig | f64HiddenBit
		q = rexp - f64ExpBias - f64SigBits
		// Fast path for small integers.
		if q <= 0 && q >= -f64SigBits {
			e := -q
			mask := uint64(1)<<uint(e) - 1
			if c&mask == 0 {
				u := c >> uint(e)
				cnt := ctz10(u)
				out, start := appendNBytes(out, cnt)
				writeDigits(u, out[start:start+cnt], cnt, false)
				return out
			}
		}
	} else {
		// subnormal
		c = rsig
		q = 1 - f64ExpBias - f64SigBits
	}

	dec := f64todec(rsig, rexp, c, q)
	return writeDec(dec, out)
}

func f64bits(f float64) uint64 { return math.Float64bits(f) }
