// Package jsonx's Schubfach float64→string formatter.
//
// Ported from ByteDance sonic's native/f64toa.c, which is in turn a port of
// Alexander Bolz's Schubfach reference C++ implementation at
// https://github.com/abolz/Drachennest.
//
// ---
// Copyright 2020 Alexander Bolz
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//
// This file may have been modified by ByteDance authors. All ByteDance
// Modifications are Copyright 2022 ByteDance Authors.
// ---
//
// Paper reference: Raffaello Giulietti, "The Schubfach way to render
// doubles" (2022-03-20). Schubfach is strictly shorter than Ryu for the
// float64 shortest-representation problem — one 128-bit multiply plus a
// round-odd step instead of Ryu's three multiplies plus exact-bits search.
package jsonx

import (
	"math"
	"math/bits"
	"unsafe"
)

const (
	f64ExpBits    = 11
	f64SigBits    = 52
	f64ExpMask    = 0x7FF0000000000000
	f64SigMask    = 0x000FFFFFFFFFFFFF
	f64ExpBias    = 1023
	f64InfNanExp  = 0x7FF
	f64HiddenBit  = 0x0010000000000000
)

// digits100 is the two-ASCII-byte lookup for 00..99 packed as uint16
// (little-endian). `digits100[k]` equals `uint16(digits[2k]) | uint16(digits[2k+1])<<8`
// — so a single 2-byte store puts the tens/ones digit pair at a buffer
// position. On amd64 this is one `movw` vs. the two `movb`s the compiler
// emits for the byte-array form (halves the store count in the digit
// emission inner loop).
var digits100 = [100]uint16{
	0x3030, 0x3130, 0x3230, 0x3330, 0x3430, 0x3530, 0x3630, 0x3730, 0x3830, 0x3930,
	0x3031, 0x3131, 0x3231, 0x3331, 0x3431, 0x3531, 0x3631, 0x3731, 0x3831, 0x3931,
	0x3032, 0x3132, 0x3232, 0x3332, 0x3432, 0x3532, 0x3632, 0x3732, 0x3832, 0x3932,
	0x3033, 0x3133, 0x3233, 0x3333, 0x3433, 0x3533, 0x3633, 0x3733, 0x3833, 0x3933,
	0x3034, 0x3134, 0x3234, 0x3334, 0x3434, 0x3534, 0x3634, 0x3734, 0x3834, 0x3934,
	0x3035, 0x3135, 0x3235, 0x3335, 0x3435, 0x3535, 0x3635, 0x3735, 0x3835, 0x3935,
	0x3036, 0x3136, 0x3236, 0x3336, 0x3436, 0x3536, 0x3636, 0x3736, 0x3836, 0x3936,
	0x3037, 0x3137, 0x3237, 0x3337, 0x3437, 0x3537, 0x3637, 0x3737, 0x3837, 0x3937,
	0x3038, 0x3138, 0x3238, 0x3338, 0x3438, 0x3538, 0x3638, 0x3738, 0x3838, 0x3938,
	0x3039, 0x3139, 0x3239, 0x3339, 0x3439, 0x3539, 0x3639, 0x3739, 0x3839, 0x3939,
}

// storeW2 writes the two-byte digit pair for k ∈ [0,99] at buf[i..i+2].
// The caller must ensure i+1 is in-bounds; the store is unsafe.
//
//go:nosplit
func storeW2(buf *byte, i int, k uint32) {
	*(*uint16)(unsafe.Pointer(uintptr(unsafe.Pointer(buf)) + uintptr(i))) = digits100[k]
}

// digits is the two-ASCII-byte lookup for 00..99. `digits[2k]` and
// `digits[2k+1]` are the tens and ones digit of k respectively.
var digits = [200]byte{
	'0', '0', '0', '1', '0', '2', '0', '3', '0', '4', '0', '5', '0', '6', '0', '7', '0', '8', '0', '9',
	'1', '0', '1', '1', '1', '2', '1', '3', '1', '4', '1', '5', '1', '6', '1', '7', '1', '8', '1', '9',
	'2', '0', '2', '1', '2', '2', '2', '3', '2', '4', '2', '5', '2', '6', '2', '7', '2', '8', '2', '9',
	'3', '0', '3', '1', '3', '2', '3', '3', '3', '4', '3', '5', '3', '6', '3', '7', '3', '8', '3', '9',
	'4', '0', '4', '1', '4', '2', '4', '3', '4', '4', '4', '5', '4', '6', '4', '7', '4', '8', '4', '9',
	'5', '0', '5', '1', '5', '2', '5', '3', '5', '4', '5', '5', '5', '6', '5', '7', '5', '8', '5', '9',
	'6', '0', '6', '1', '6', '2', '6', '3', '6', '4', '6', '5', '6', '6', '6', '7', '6', '8', '6', '9',
	'7', '0', '7', '1', '7', '2', '7', '3', '7', '4', '7', '5', '7', '6', '7', '7', '7', '8', '7', '9',
	'8', '0', '8', '1', '8', '2', '8', '3', '8', '4', '8', '5', '8', '6', '8', '7', '8', '8', '8', '9',
	'9', '0', '9', '1', '9', '2', '9', '3', '9', '4', '9', '5', '9', '6', '9', '7', '9', '8', '9', '9',
}

// schubfachDec is the decoded Schubfach intermediate: sig * 10^exp.
type schubfachDec struct {
	sig uint64
	exp int32
}

// ctz10 returns the number of decimal digits in v (must be in [1, 1e17]).
func ctz10(v uint64) int {
	if v >= 10000000000 {
		switch {
		case v < 100000000000:
			return 11
		case v < 1000000000000:
			return 12
		case v < 10000000000000:
			return 13
		case v < 100000000000000:
			return 14
		case v < 1000000000000000:
			return 15
		case v < 10000000000000000:
			return 16
		default:
			return 17
		}
	}
	switch {
	case v < 10:
		return 1
	case v < 100:
		return 2
	case v < 1000:
		return 3
	case v < 10000:
		return 4
	case v < 100000:
		return 5
	case v < 1000000:
		return 6
	case v < 10000000:
		return 7
	case v < 100000000:
		return 8
	case v < 1000000000:
		return 9
	default:
		return 10
	}
}

// roundOdd computes the Schubfach round-odd step: returns y1 | (y0 > 1)
// where y = cp * (pow10Hi:pow10Lo) >> 64, done in 128 bits.
func roundOdd(pow10Hi, pow10Lo, cp uint64) uint64 {
	// x = cp * pow10Lo (128 bits)
	xHi, _ := bits.Mul64(cp, pow10Lo)
	// y = cp * pow10Hi + xHi  (128 bits)
	yHi, yLo := bits.Mul64(cp, pow10Hi)
	yLoSum, carry := bits.Add64(yLo, xHi, 0)
	yHi, _ = bits.Add64(yHi, 0, carry)
	y0 := yLoSum
	y1 := yHi
	if y0 > 1 {
		return y1 | 1
	}
	return y1
}

// f64todec applies the Schubfach algorithm to the raw float64 bits.
// Returns dec such that fp ≈ sig * 10^exp (the exact-shortest form).
func f64todec(rsig uint64, rexp int32, c uint64, q int32) schubfachDec {
	even := c&1 == 0
	irregular := rsig == 0 && rexp > 1

	cbl := 4*c - 2
	if irregular {
		cbl = 4*c - 1
	}
	cb := 4 * c
	cbr := 4*c + 2

	// k = irregular ? floor(log10(3/4 * 2^q)) : floor(log10(2^q))
	var k int32
	if irregular {
		k = (q*1262611 - 524031) >> 22
	} else {
		k = (q * 1262611) >> 22
	}

	h := q + (((-k) * 1741647) >> 19) + 1

	// pow10_ceil_sig lookup: index is (-k) shifted by schubfachKMin.
	idx := -k - schubfachKMin
	pow10Hi := schubfachPow10CeilSig[idx][0]
	pow10Lo := schubfachPow10CeilSig[idx][1]

	vbl := roundOdd(pow10Hi, pow10Lo, cbl<<uint(h))
	vb := roundOdd(pow10Hi, pow10Lo, cb<<uint(h))
	vbr := roundOdd(pow10Hi, pow10Lo, cbr<<uint(h))

	lower := vbl
	upper := vbr
	if !even {
		lower++
		upper--
	}

	s := vb / 4
	if s >= 10 {
		// R_{k+1} may contain up or wp.
		sp := s / 10
		upInside := lower <= 40*sp
		wpInside := 40*sp+40 <= upper
		if upInside != wpInside {
			exp := k + 1
			if wpInside {
				return schubfachDec{sig: sp + 1, exp: exp}
			}
			return schubfachDec{sig: sp, exp: exp}
		}
	}

	uInside := lower <= 4*s
	wInside := 4*s+4 <= upper
	if uInside != wInside {
		if wInside {
			return schubfachDec{sig: s + 1, exp: k}
		}
		return schubfachDec{sig: s, exp: k}
	}

	// Both u and w inside: round to nearest, tie to even.
	mid := 4*s + 2
	roundUp := vb > mid || (vb == mid && s&1 != 0)
	if roundUp {
		return schubfachDec{sig: s + 1, exp: k}
	}
	return schubfachDec{sig: s, exp: k}
}

// writeDigits fills exactly cnt decimal digits of sig into dst[0:cnt],
// most-significant first. dst must have length ≥ cnt.
// If trimTrailingZeros is true, returns the number of non-zero tail
// digits produced (so caller can shorten the emitted range); otherwise
// returns cnt verbatim. Trailing zeros, when trimmed, are in blocks of
// 8 (matching sonic's trick — only the outermost 8 digits are tested
// for being all-zero).
func writeDigits(sig uint64, dst []byte, cnt int, trimTrailingZeros bool) int {
	p := cnt
	ctz := 0

	if (sig >> 32) != 0 {
		q := sig / 100000000
		r := uint32(sig) - 100000000*uint32(q)
		sig = q
		if trimTrailingZeros && r == 0 {
			ctz += 8
		} else {
			c := r % 10000
			r /= 10000
			d := r % 10000
			c0 := (c % 100) << 1
			c1 := (c / 100) << 1
			d0 := (d % 100) << 1
			d1 := (d / 100) << 1
			dst[p-2] = digits[c0]
			dst[p-1] = digits[c0+1]
			dst[p-4] = digits[c1]
			dst[p-3] = digits[c1+1]
			dst[p-6] = digits[d0]
			dst[p-5] = digits[d0+1]
			dst[p-8] = digits[d1]
			dst[p-7] = digits[d1+1]
		}
		p -= 8
	}

	sig2 := uint32(sig)
	for sig2 >= 10000 {
		c := sig2 - 10000*(sig2/10000)
		sig2 /= 10000
		c0 := (c % 100) << 1
		c1 := (c / 100) << 1
		dst[p-2] = digits[c0]
		dst[p-1] = digits[c0+1]
		dst[p-4] = digits[c1]
		dst[p-3] = digits[c1+1]
		p -= 4
	}
	if sig2 >= 100 {
		c := (sig2 % 100) << 1
		sig2 /= 100
		dst[p-2] = digits[c]
		dst[p-1] = digits[c+1]
		p -= 2
	}
	if sig2 >= 10 {
		c := sig2 << 1
		dst[p-2] = digits[c]
		dst[p-1] = digits[c+1]
	} else {
		dst[0] = byte('0' + sig2)
	}
	return cnt - ctz
}

// writeDigitsStack emits cnt decimal digits of sig into buf[0:cnt]
// (most-significant first) with compile-proven bounds on a fixed-size
// stack array. When trim is true, collapses a trailing 8-zero block.
// Returns the number of digits actually written (cnt or cnt-8).
//
// Uses the packed uint16 `digits100` LUT to emit two ASCII digits per
// 16-bit store (one `movw`), halving the store count vs. per-byte lookup.
//
// This is the pure-Go implementation used on non-amd64 and for short
// significands (cnt < 8) where the amd64 asm kernel's call overhead
// would dominate. writeDigitsFast is the dispatch entry point.
func writeDigitsStack(sig uint64, buf *[24]byte, cnt int, trim bool) int {
	base := (*byte)(unsafe.Pointer(&buf[0]))
	p := cnt
	ctz := 0
	if (sig >> 32) != 0 {
		q := sig / 100000000
		r := uint32(sig) - 100000000*uint32(q)
		sig = q
		if trim && r == 0 {
			ctz = 8
		} else {
			c := r % 10000
			d := r / 10000
			storeW2(base, p-2, c%100)
			storeW2(base, p-4, c/100)
			storeW2(base, p-6, d%100)
			storeW2(base, p-8, d/100)
		}
		p -= 8
	}
	sig2 := uint32(sig)
	for sig2 >= 10000 {
		r := sig2 - 10000*(sig2/10000)
		sig2 /= 10000
		storeW2(base, p-2, r%100)
		storeW2(base, p-4, r/100)
		p -= 4
	}
	if sig2 >= 100 {
		storeW2(base, p-2, sig2%100)
		sig2 /= 100
		p -= 2
	}
	if sig2 >= 10 {
		storeW2(base, p-2, sig2)
	} else {
		buf[0] = byte('0' + sig2)
	}
	return cnt - ctz
}

// zeroPad is a reusable buffer of ASCII '0' bytes for padding
// leading/trailing zeros via a single append.
var zeroPad = [32]byte{
	'0', '0', '0', '0', '0', '0', '0', '0',
	'0', '0', '0', '0', '0', '0', '0', '0',
	'0', '0', '0', '0', '0', '0', '0', '0',
	'0', '0', '0', '0', '0', '0', '0', '0',
}

// formatExponent writes v in scientific form: d.dddde±NN. Appends to
// out and returns the extended slice.
func formatExponent(dec schubfachDec, out []byte, cnt int) []byte {
	var buf [24]byte
	n := writeDigitsFast(dec.sig, &buf, cnt, true)
	// buf[0] is the leading digit; buf[1:n] is the rest. Insert '.' between.
	out = append(out, buf[0])
	if n > 1 {
		out = append(out, '.')
		out = append(out, buf[1:n]...)
	}
	out = append(out, 'e')
	exp := dec.exp + int32(cnt) - 1
	if exp < 0 {
		out = append(out, '-')
		exp = -exp
	} else {
		out = append(out, '+')
	}
	if exp >= 100 {
		c := exp % 10
		idx := (exp / 10) * 2
		out = append(out, digits[idx], digits[idx+1], byte('0'+c))
	} else if exp >= 10 {
		idx := exp * 2
		out = append(out, digits[idx], digits[idx+1])
	} else {
		out = append(out, byte('0'+exp))
	}
	return out
}

// formatDecimal writes v in fixed-point notation with a decimal point.
// Uses a 24-byte stack scratch so the significand digits are emitted
// once into compile-proven bounds, then blitted into `out` in a single
// append per segment — no post-hoc shift-copy to insert '.'.
func formatDecimal(dec schubfachDec, out []byte, cnt int) []byte {
	var buf [24]byte
	n := writeDigitsFast(dec.sig, &buf, cnt, true)
	point := cnt + int(dec.exp)

	if point <= 0 {
		// "0.000…0dddd" — one '0', '.', -point zeros, then significand.
		out = append(out, '0', '.')
		if -point > 0 {
			out = append(out, zeroPad[:-point]...)
		}
		return append(out, buf[:n]...)
	}

	if n > point {
		// integer part [0:point], '.', fraction [point:n]
		out = append(out, buf[:point]...)
		out = append(out, '.')
		return append(out, buf[point:n]...)
	}
	// n <= point: pad integer part with zeros after the significand.
	out = append(out, buf[:n]...)
	if point-n > 0 {
		out = append(out, zeroPad[:point-n]...)
	}
	return out
}

// writeDec is the Schubfach "format decision" wrapper: pick scientific
// vs. decimal based on the magnitude.
func writeDec(dec schubfachDec, out []byte) []byte {
	cnt := ctz10(dec.sig)
	dot := cnt + int(dec.exp)
	sciExp := dot - 1
	expFmt := sciExp < -6 || sciExp > 20
	hasDot := dot < cnt

	if expFmt {
		return formatExponent(dec, out, cnt)
	}
	if hasDot {
		return formatDecimal(dec, out, cnt)
	}
	// Pure integer (possibly trailing zeros to reach `dot` width).
	var buf [24]byte
	writeDigitsFast(dec.sig, &buf, cnt, false)
	out = append(out, buf[:cnt]...)
	if dot > cnt {
		out = append(out, zeroPad[:dot-cnt]...)
	}
	return out
}

// schubfachAppendFloat64 appends the decimal representation of f to out.
// Matches the general contract of strconv.AppendFloat(_, f, 'g', -1, 64)
// but with Schubfach-style exponent-format gating (matches sonic's
// choice: 'e' when scientific exponent < -6 or > 20).
func schubfachAppendFloat64(out []byte, f float64) []byte {
	raw := f64bits(f)
	neg := raw>>63 != 0
	rsig := raw & f64SigMask
	rexp := int32((raw & f64ExpMask) >> f64SigBits)

	// NaN/Inf: caller checks, but for safety return empty.
	if rexp == f64InfNanExp {
		return out
	}

	if neg {
		out = append(out, '-')
	}

	// zero
	if raw<<1 == 0 {
		return append(out, '0')
	}

	var c uint64
	var q int32
	if rexp != 0 {
		c = rsig | f64HiddenBit
		q = rexp - f64ExpBias - f64SigBits
		// Fast path for small integers.
		if q <= 0 && q >= -f64SigBits {
			e := -q
			mask := uint64(1)<<uint(e) - 1
			if c&mask == 0 {
				u := c >> uint(e)
				cnt := ctz10(u)
				var buf [24]byte
				writeDigitsFast(u, &buf, cnt, false)
				return append(out, buf[:cnt]...)
			}
		}
	} else {
		// subnormal
		c = rsig
		q = 1 - f64ExpBias - f64SigBits
	}

	dec := f64todec(rsig, rexp, c, q)
	// Post-trim trailing zeros. Schubfach's inner loop only does one
	// upward step (s→s/10 when R_{k+1} still contains exactly one
	// endpoint); for values like -141.002991 the Schubfach `s` can
	// still end in multiple trailing zeros that the Drachennest
	// reference strips via an iterative loop. We do the same here —
	// parses identical, but now bit-shortest (and 7 fewer chars per
	// such value in the JSON output).
	for dec.sig >= 10 && dec.sig%10 == 0 {
		dec.sig /= 10
		dec.exp++
	}
	return writeDec(dec, out)
}

func f64bits(f float64) uint64 { return math.Float64bits(f) }
