// Code generated by command: go run gen.go -out /home/debian/json/scan_amd64.s -pkg fastjson. DO NOT EDIT.

#include "textflag.h"

// func scanStringAVX512(p *byte, n int) int
// Requires: AVX, AVX512BW, AVX512F, BMI
TEXT ·scanStringAVX512(SB), NOSPLIT, $0-24
	MOVQ         p+0(FP), AX
	MOVQ         n+8(FP), CX
	XORQ         DX, DX
	MOVQ         $0x00000022, BX
	VPBROADCASTB BX, Z0
	MOVQ         $0x0000005c, BX
	VPBROADCASTB BX, Z1
	MOVQ         $0x00000020, BX
	VPBROADCASTB BX, Z2

loop:
	MOVQ      CX, BX
	SUBQ      DX, BX
	CMPQ      BX, $0x00000040
	JL        tail
	VMOVDQU64 (AX)(DX*1), Z3
	VPCMPEQB  Z0, Z3, K1
	VPCMPEQB  Z1, Z3, K2
	KORQ      K1, K2, K1
	VPCMPUB   $0x01, Z2, Z3, K2
	KORQ      K1, K2, K1
	KTESTQ    K1, K1
	JNZ       found64
	ADDQ      $0x00000040, DX
	JMP       loop

found64:
	KMOVQ  K1, AX
	TZCNTQ AX, AX
	ADDQ   AX, DX
	MOVQ   DX, ret+16(FP)
	VZEROUPPER
	RET

tail:
tail_loop:
	CMPQ DX, CX
	JGE  notfound
	MOVB (AX)(DX*1), BL
	CMPB BL, $0x22
	JE   done
	CMPB BL, $0x5c
	JE   done
	CMPB BL, $0x20
	JB   done
	INCQ DX
	JMP  tail_loop

notfound:
done:
	MOVQ DX, ret+16(FP)
	VZEROUPPER
	RET
