// Code generated by command: go run gen_skipws.go -out /home/debian/json/skipws_amd64.s -pkg fastjson. DO NOT EDIT.

#include "textflag.h"

// func skipWSAVX512(p *byte, n int) int
// Requires: AVX, AVX512BW, AVX512F, BMI
TEXT ·skipWSAVX512(SB), NOSPLIT, $0-24
	MOVQ         p+0(FP), AX
	MOVQ         n+8(FP), CX
	XORQ         DX, DX
	MOVQ         $0x00000020, BX
	VPBROADCASTB BX, Z0
	MOVQ         $0x00000009, BX
	VPBROADCASTB BX, Z1
	MOVQ         $0x0000000a, BX
	VPBROADCASTB BX, Z2
	MOVQ         $0x0000000d, BX
	VPBROADCASTB BX, Z3

loop:
	MOVQ      CX, BX
	SUBQ      DX, BX
	CMPQ      BX, $0x00000040
	JL        tail
	VMOVDQU64 (AX)(DX*1), Z4
	VPCMPEQB  Z0, Z4, K1
	VPCMPEQB  Z1, Z4, K2
	VPCMPEQB  Z2, Z4, K3
	VPCMPEQB  Z3, Z4, K4
	KORQ      K1, K2, K1
	KORQ      K1, K3, K1
	KORQ      K1, K4, K1
	KNOTQ     K1, K1
	KTESTQ    K1, K1
	JNZ       found64
	ADDQ      $0x00000040, DX
	JMP       loop

found64:
	KMOVQ  K1, AX
	TZCNTQ AX, AX
	ADDQ   AX, DX
	MOVQ   DX, ret+16(FP)
	VZEROUPPER
	RET

tail:
tail_loop:
	CMPQ DX, CX
	JGE  notfound
	MOVB (AX)(DX*1), BL
	CMPB BL, $0x20
	JE   next
	CMPB BL, $0x09
	JE   next
	CMPB BL, $0x0a
	JE   next
	CMPB BL, $0x0d
	JE   next
	JMP  done

next:
	INCQ DX
	JMP  tail_loop

notfound:
done:
	MOVQ DX, ret+16(FP)
	VZEROUPPER
	RET
