// Code generated by command: go run gen_writedigits.go -out /home/debian/json/writedigits_amd64.s -pkg fastjson. DO NOT EDIT.

#include "textflag.h"

// func writeDigitsAsm(sig uint64, buf *byte, cnt uint64, trim uint64, tab *uint16) uint64
TEXT ·writeDigitsAsm(SB), NOSPLIT, $0-48
	MOVQ  sig+0(FP), CX
	MOVQ  buf+8(FP), BX
	MOVQ  cnt+16(FP), AX
	MOVQ  trim+24(FP), SI
	MOVQ  tab+32(FP), DI
	MOVQ  AX, R8
	MOVQ  AX, R9
	MOVQ  CX, AX
	SHRQ  $0x20, AX
	TESTQ AX, AX
	JZ    loop4
	MOVQ  $0x0000000005f5e100, R10
	XORQ  DX, DX
	MOVQ  CX, AX
	DIVQ  R10
	MOVQ  AX, CX
	MOVQ  DX, AX
	TESTQ SI, SI
	JZ    emit8
	TESTQ AX, AX
	JNZ   emit8
	SUBQ  $0x00000008, R9
	SUBQ  $0x00000008, R8
	JMP   loop4

emit8:
	MOVQ    $0x0000000000002710, SI
	XORQ    DX, DX
	DIVQ    SI
	MOVQ    DX, DX
	IMUL3Q  $0x000028f6, DX, SI
	SHRQ    $0x14, SI
	IMUL3Q  $0x64, SI, R10
	SUBQ    R10, DX
	MOVWQZX (DI)(DX*2), DX
	MOVW    DX, -2(BX)(R8*1)
	MOVWQZX (DI)(SI*2), DX
	MOVW    DX, -4(BX)(R8*1)
	IMUL3Q  $0x000028f6, AX, DX
	SHRQ    $0x14, DX
	IMUL3Q  $0x64, DX, SI
	SUBQ    SI, AX
	MOVWQZX (DI)(AX*2), AX
	MOVW    AX, -6(BX)(R8*1)
	MOVWQZX (DI)(DX*2), AX
	MOVW    AX, -8(BX)(R8*1)
	SUBQ    $0x00000008, R8

loop4:
	CMPQ    CX, $0x00002710
	JL      tail
	MOVQ    $0x0000000000002710, SI
	XORQ    DX, DX
	MOVQ    CX, AX
	DIVQ    SI
	MOVQ    AX, CX
	MOVQ    DX, AX
	IMUL3Q  $0x000028f6, AX, DX
	SHRQ    $0x14, DX
	IMUL3Q  $0x64, DX, SI
	SUBQ    SI, AX
	MOVWQZX (DI)(AX*2), AX
	MOVW    AX, -2(BX)(R8*1)
	MOVWQZX (DI)(DX*2), AX
	MOVW    AX, -4(BX)(R8*1)
	SUBQ    $0x00000004, R8
	JMP     loop4

tail:
	CMPQ    CX, $0x00000064
	JL      under100
	IMUL3Q  $0x000028f6, CX, AX
	SHRQ    $0x14, AX
	IMUL3Q  $0x64, AX, DX
	SUBQ    DX, CX
	MOVWQZX (DI)(CX*2), CX
	MOVW    CX, -2(BX)(R8*1)
	SUBQ    $0x00000002, R8
	MOVQ    AX, CX

under100:
	CMPQ    CX, $0x0000000a
	JL      single
	MOVWQZX (DI)(CX*2), AX
	MOVW    AX, -2(BX)(R8*1)
	JMP     done

single:
	ADDQ $0x00000030, CX
	MOVQ CX, AX
	MOVB AL, -1(BX)(R8*1)

done:
	MOVQ R9, ret+40(FP)
	RET
